[package]
name = "your/project"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]

[place]
shared-packages = "game.ReplicatedStorage.Packages"
